# Generated by Django 2.2 on 2022-10-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_messages', '0003_message_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='executor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
