# Generated by Django 2.2 on 2022-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_messages', '0005_message_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
